version: '3'

services:
  auth:
    env_file:
      - .env
    build:
      context:
        ./auth-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8001:8001
  weather:
    env_file:
      - .env
    build:
      context:
        ./weather-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8002:8002
