version: '3'

services:
  auth:
    env_file:
      - .env
    build:
      context:
        ./auth-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8001:8001"
  weather:
    env_file:
      - .env
    build:
      context:
        ./weather-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8002:8002"
  shortener:
    env_file:
      - .env
    build:
      context:
        ./shortener-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8003:8003"
    depends_on:
      - auth
  frontend:
    env_file:
      - .env
    build:
      context:
        ./frontend-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:3000"
