version: '3'

services:
  auth:
    env_file:
      - .env
    build:
      context:
        .
      dockerfile:
        ./auth-service/Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
#    ports:
#      - "8001:8001"
#  weather:
#    env_file:
#      - .env
#    build:
#      context:
#        ./weather-service
#      dockerfile:
#        ./Dockerfile
#    restart: always
#    deploy:
#      mode: replicated
#      replicas: 1
#    ports:
#      - "8002:8002"
#  shortener:
#    env_file:
#      - .env
#    build:
#      context:
#        ./shortener-service
#      dockerfile:
#        ./Dockerfile
#    restart: always
#    deploy:
#      mode: replicated
#      replicas: 1
#    ports:
#      - "8003:8003"
#    depends_on:
#      - auth
  qrcode:
    env_file:
      - .env
    build:
      context:
        ./qrcode-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
#    ports:
#      - "8000:8000"
  broker:
    env_file:
      - .env
    build:
      context:
        ./broker-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3000:3000"
  frontend:
    env_file:
      - .env
    build:
      context:
        ./frontend-service
      dockerfile:
        ./Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
