version: '3'

services:
  auth:
    env_file:
      - .env
    build:
      context:
        .
      dockerfile:
        ./auth-service/Dockerfile
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./auth-service/cmd
    deploy:
      mode: replicated
      replicas: 1

#  weather:
#    env_file:
#      - .env
#    build:
#      context:
#        ./weather-service
#      dockerfile:
#        ./Dockerfile
#    restart: always
#    deploy:
#      mode: replicated
#      replicas: 1

  shortener:
    env_file:
      - .env
    build:
      context:
        ./shortener-service
      dockerfile:
        ./Dockerfile
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./shortener-service/cmd
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - auth

  qrcode:
    env_file:
      - .env
    build:
      context:
        ./qrcode-service
      dockerfile:
        ./Dockerfile
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./qrcode-service/cmd
    deploy:
      mode: replicated
      replicas: 1

  broker:
    env_file:
      - .env
    build:
      context:
        ./broker-service
      dockerfile:
        ./Dockerfile
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./broker-service/cmd
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3000:3000"

  frontend:
    env_file:
      - .env
    build:
      context:
        ./frontend-service
      dockerfile:
        ./Dockerfile
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./frontend-service/cmd
          ignore:
            - ./frontend-service/cmd/templates
            - ./frontend-service/cmd/public
            - ./frontend-service/cmd/data/mainPageData.json
        - action: sync
          path: ./frontend-service/cmd/templates
          target: /app/cmd/web/templates
        - action: sync
          path: ./frontend-service/cmd/public
          target: /app/cmd/web/public
        - action: sync
          path: ./frontend-service/cmd/data/mainPageData.json
          target: /app/cmd/web/data
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"

