// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: cmd/shortener/shortener.proto

package shortener

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShortenerServiceClient is the client API for ShortenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortenerServiceClient interface {
	GetOne(ctx context.Context, in *ShortenerGetOneRequest, opts ...grpc.CallOption) (*ShortenerGetOneResponse, error)
	GetAll(ctx context.Context, in *ShortenerGetAllRequest, opts ...grpc.CallOption) (*ShortenerGetAllResponse, error)
	Insert(ctx context.Context, in *ShortenerInsertRequest, opts ...grpc.CallOption) (*ShortenerInsertResponse, error)
	Delete(ctx context.Context, in *ShortenerDeleteRequest, opts ...grpc.CallOption) (*ShortenerDeleteResponse, error)
}

type shortenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerServiceClient(cc grpc.ClientConnInterface) ShortenerServiceClient {
	return &shortenerServiceClient{cc}
}

func (c *shortenerServiceClient) GetOne(ctx context.Context, in *ShortenerGetOneRequest, opts ...grpc.CallOption) (*ShortenerGetOneResponse, error) {
	out := new(ShortenerGetOneResponse)
	err := c.cc.Invoke(ctx, "/shortener.ShortenerService/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerServiceClient) GetAll(ctx context.Context, in *ShortenerGetAllRequest, opts ...grpc.CallOption) (*ShortenerGetAllResponse, error) {
	out := new(ShortenerGetAllResponse)
	err := c.cc.Invoke(ctx, "/shortener.ShortenerService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerServiceClient) Insert(ctx context.Context, in *ShortenerInsertRequest, opts ...grpc.CallOption) (*ShortenerInsertResponse, error) {
	out := new(ShortenerInsertResponse)
	err := c.cc.Invoke(ctx, "/shortener.ShortenerService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerServiceClient) Delete(ctx context.Context, in *ShortenerDeleteRequest, opts ...grpc.CallOption) (*ShortenerDeleteResponse, error) {
	out := new(ShortenerDeleteResponse)
	err := c.cc.Invoke(ctx, "/shortener.ShortenerService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServiceServer is the server API for ShortenerService service.
// All implementations must embed UnimplementedShortenerServiceServer
// for forward compatibility
type ShortenerServiceServer interface {
	GetOne(context.Context, *ShortenerGetOneRequest) (*ShortenerGetOneResponse, error)
	GetAll(context.Context, *ShortenerGetAllRequest) (*ShortenerGetAllResponse, error)
	Insert(context.Context, *ShortenerInsertRequest) (*ShortenerInsertResponse, error)
	Delete(context.Context, *ShortenerDeleteRequest) (*ShortenerDeleteResponse, error)
	mustEmbedUnimplementedShortenerServiceServer()
}

// UnimplementedShortenerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShortenerServiceServer struct {
}

func (UnimplementedShortenerServiceServer) GetOne(context.Context, *ShortenerGetOneRequest) (*ShortenerGetOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedShortenerServiceServer) GetAll(context.Context, *ShortenerGetAllRequest) (*ShortenerGetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedShortenerServiceServer) Insert(context.Context, *ShortenerInsertRequest) (*ShortenerInsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedShortenerServiceServer) Delete(context.Context, *ShortenerDeleteRequest) (*ShortenerDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedShortenerServiceServer) mustEmbedUnimplementedShortenerServiceServer() {}

// UnsafeShortenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortenerServiceServer will
// result in compilation errors.
type UnsafeShortenerServiceServer interface {
	mustEmbedUnimplementedShortenerServiceServer()
}

func RegisterShortenerServiceServer(s grpc.ServiceRegistrar, srv ShortenerServiceServer) {
	s.RegisterService(&ShortenerService_ServiceDesc, srv)
}

func _ShortenerService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenerGetOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.ShortenerService/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).GetOne(ctx, req.(*ShortenerGetOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenerGetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.ShortenerService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).GetAll(ctx, req.(*ShortenerGetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenerInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.ShortenerService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).Insert(ctx, req.(*ShortenerInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortenerService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shortener.ShortenerService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServiceServer).Delete(ctx, req.(*ShortenerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShortenerService_ServiceDesc is the grpc.ServiceDesc for ShortenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShortenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shortener.ShortenerService",
	HandlerType: (*ShortenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _ShortenerService_GetOne_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ShortenerService_GetAll_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _ShortenerService_Insert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ShortenerService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/shortener/shortener.proto",
}
