// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: rpc/qrcode.proto

package qrcode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QRCodeServiceClient is the client API for QRCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QRCodeServiceClient interface {
	GetQRCode(ctx context.Context, in *QRCodeRequest, opts ...grpc.CallOption) (*QRCodeResponse, error)
}

type qRCodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQRCodeServiceClient(cc grpc.ClientConnInterface) QRCodeServiceClient {
	return &qRCodeServiceClient{cc}
}

func (c *qRCodeServiceClient) GetQRCode(ctx context.Context, in *QRCodeRequest, opts ...grpc.CallOption) (*QRCodeResponse, error) {
	out := new(QRCodeResponse)
	err := c.cc.Invoke(ctx, "/logs.QRCodeService/GetQRCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QRCodeServiceServer is the server API for QRCodeService service.
// All implementations must embed UnimplementedQRCodeServiceServer
// for forward compatibility
type QRCodeServiceServer interface {
	GetQRCode(context.Context, *QRCodeRequest) (*QRCodeResponse, error)
	mustEmbedUnimplementedQRCodeServiceServer()
}

// UnimplementedQRCodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQRCodeServiceServer struct {
}

func (UnimplementedQRCodeServiceServer) GetQRCode(context.Context, *QRCodeRequest) (*QRCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQRCode not implemented")
}
func (UnimplementedQRCodeServiceServer) mustEmbedUnimplementedQRCodeServiceServer() {}

// UnsafeQRCodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QRCodeServiceServer will
// result in compilation errors.
type UnsafeQRCodeServiceServer interface {
	mustEmbedUnimplementedQRCodeServiceServer()
}

func RegisterQRCodeServiceServer(s grpc.ServiceRegistrar, srv QRCodeServiceServer) {
	s.RegisterService(&QRCodeService_ServiceDesc, srv)
}

func _QRCodeService_GetQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRCodeServiceServer).GetQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logs.QRCodeService/GetQRCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRCodeServiceServer).GetQRCode(ctx, req.(*QRCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QRCodeService_ServiceDesc is the grpc.ServiceDesc for QRCodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QRCodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logs.QRCodeService",
	HandlerType: (*QRCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQRCode",
			Handler:    _QRCodeService_GetQRCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/qrcode.proto",
}
