// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: cmd/shortener/shortener.proto

package shortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenerInsertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long  string `protobuf:"bytes,1,opt,name=long,proto3" json:"long,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ShortenerInsertRequest) Reset() {
	*x = ShortenerInsertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerInsertRequest) ProtoMessage() {}

func (x *ShortenerInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerInsertRequest.ProtoReflect.Descriptor instead.
func (*ShortenerInsertRequest) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenerInsertRequest) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *ShortenerInsertRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ShortenerDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ShortenerDeleteRequest) Reset() {
	*x = ShortenerDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerDeleteRequest) ProtoMessage() {}

func (x *ShortenerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerDeleteRequest.ProtoReflect.Descriptor instead.
func (*ShortenerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenerDeleteRequest) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *ShortenerDeleteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ShortenerGetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *ShortenerGetOneRequest) Reset() {
	*x = ShortenerGetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerGetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerGetOneRequest) ProtoMessage() {}

func (x *ShortenerGetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerGetOneRequest.ProtoReflect.Descriptor instead.
func (*ShortenerGetOneRequest) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenerGetOneRequest) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type ShortenerGetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ShortenerGetAllRequest) Reset() {
	*x = ShortenerGetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerGetAllRequest) ProtoMessage() {}

func (x *ShortenerGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerGetAllRequest.ProtoReflect.Descriptor instead.
func (*ShortenerGetAllRequest) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenerGetAllRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ShortenerInsertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *ShortenerInsertResponse) Reset() {
	*x = ShortenerInsertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerInsertResponse) ProtoMessage() {}

func (x *ShortenerInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerInsertResponse.ProtoReflect.Descriptor instead.
func (*ShortenerInsertResponse) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenerInsertResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type ShortenerGetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Long string `protobuf:"bytes,1,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *ShortenerGetOneResponse) Reset() {
	*x = ShortenerGetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerGetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerGetOneResponse) ProtoMessage() {}

func (x *ShortenerGetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerGetOneResponse.ProtoReflect.Descriptor instead.
func (*ShortenerGetOneResponse) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenerGetOneResponse) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type ShortenerRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	Long  string `protobuf:"bytes,2,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *ShortenerRow) Reset() {
	*x = ShortenerRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerRow) ProtoMessage() {}

func (x *ShortenerRow) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerRow.ProtoReflect.Descriptor instead.
func (*ShortenerRow) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *ShortenerRow) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *ShortenerRow) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

type ShortenerGetAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*ShortenerRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *ShortenerGetAllResponse) Reset() {
	*x = ShortenerGetAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerGetAllResponse) ProtoMessage() {}

func (x *ShortenerGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerGetAllResponse.ProtoReflect.Descriptor instead.
func (*ShortenerGetAllResponse) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *ShortenerGetAllResponse) GetRows() []*ShortenerRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ShortenerDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShortenerDeleteResponse) Reset() {
	*x = ShortenerDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_shortener_shortener_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenerDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenerDeleteResponse) ProtoMessage() {}

func (x *ShortenerDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_shortener_shortener_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenerDeleteResponse.ProtoReflect.Descriptor instead.
func (*ShortenerDeleteResponse) Descriptor() ([]byte, []int) {
	return file_cmd_shortener_shortener_proto_rawDescGZIP(), []int{8}
}

var File_cmd_shortener_shortener_proto protoreflect.FileDescriptor

var file_cmd_shortener_shortener_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6d, 0x64, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x16, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x44,
	0x0a, 0x16, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2e, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x22, 0x2e, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2f, 0x0a, 0x17, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x22, 0x2d, 0x0a, 0x17, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x38, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x52, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x46,
	0x0a, 0x17, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x6f, 0x77,
	0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xd6, 0x02, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65,
	0x12, 0x21, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_shortener_shortener_proto_rawDescOnce sync.Once
	file_cmd_shortener_shortener_proto_rawDescData = file_cmd_shortener_shortener_proto_rawDesc
)

func file_cmd_shortener_shortener_proto_rawDescGZIP() []byte {
	file_cmd_shortener_shortener_proto_rawDescOnce.Do(func() {
		file_cmd_shortener_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_shortener_shortener_proto_rawDescData)
	})
	return file_cmd_shortener_shortener_proto_rawDescData
}

var file_cmd_shortener_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cmd_shortener_shortener_proto_goTypes = []interface{}{
	(*ShortenerInsertRequest)(nil),  // 0: shortener.ShortenerInsertRequest
	(*ShortenerDeleteRequest)(nil),  // 1: shortener.ShortenerDeleteRequest
	(*ShortenerGetOneRequest)(nil),  // 2: shortener.ShortenerGetOneRequest
	(*ShortenerGetAllRequest)(nil),  // 3: shortener.ShortenerGetAllRequest
	(*ShortenerInsertResponse)(nil), // 4: shortener.ShortenerInsertResponse
	(*ShortenerGetOneResponse)(nil), // 5: shortener.ShortenerGetOneResponse
	(*ShortenerRow)(nil),            // 6: shortener.ShortenerRow
	(*ShortenerGetAllResponse)(nil), // 7: shortener.ShortenerGetAllResponse
	(*ShortenerDeleteResponse)(nil), // 8: shortener.ShortenerDeleteResponse
}
var file_cmd_shortener_shortener_proto_depIdxs = []int32{
	6, // 0: shortener.ShortenerGetAllResponse.rows:type_name -> shortener.ShortenerRow
	2, // 1: shortener.ShortenerService.GetOne:input_type -> shortener.ShortenerGetOneRequest
	3, // 2: shortener.ShortenerService.GetAll:input_type -> shortener.ShortenerGetAllRequest
	0, // 3: shortener.ShortenerService.Insert:input_type -> shortener.ShortenerInsertRequest
	1, // 4: shortener.ShortenerService.Delete:input_type -> shortener.ShortenerDeleteRequest
	5, // 5: shortener.ShortenerService.GetOne:output_type -> shortener.ShortenerGetOneResponse
	7, // 6: shortener.ShortenerService.GetAll:output_type -> shortener.ShortenerGetAllResponse
	4, // 7: shortener.ShortenerService.Insert:output_type -> shortener.ShortenerInsertResponse
	8, // 8: shortener.ShortenerService.Delete:output_type -> shortener.ShortenerDeleteResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_shortener_shortener_proto_init() }
func file_cmd_shortener_shortener_proto_init() {
	if File_cmd_shortener_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_shortener_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerInsertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerGetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerGetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerInsertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerGetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerGetAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_shortener_shortener_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenerDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_shortener_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_shortener_shortener_proto_goTypes,
		DependencyIndexes: file_cmd_shortener_shortener_proto_depIdxs,
		MessageInfos:      file_cmd_shortener_shortener_proto_msgTypes,
	}.Build()
	File_cmd_shortener_shortener_proto = out.File
	file_cmd_shortener_shortener_proto_rawDesc = nil
	file_cmd_shortener_shortener_proto_goTypes = nil
	file_cmd_shortener_shortener_proto_depIdxs = nil
}
